notifications:
  email: false
language: node_js
node_js:
- "6"
script:
  - "NODE_ENV=test npm run-script unit-tests"
  - "npm run-script style"
cache:
- apt: true
- directories:
  - "$HOME/.npm"
  - "$HOME/.electron"
  - "/Library/Caches/Homebrew"
env:
  - CC=clang CXX=clang++ npm_config_clang=1
addons:
  apt:
    packages:
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev
before_install:
  - "npm config set spin false"
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
  - ./node_modules/.bin/electron-rebuild
  - sudo service dbus start
  - eval $(gnome-keyring-daemon)
  - export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
